<!DOCTYPE html>
<html>
    <head>
        <title>The Next Social</title>
        <!-- Load Twitter Bootstrap and jQuery -->
        <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
        <link rel="stylesheet" href="css/style.css">
        <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    </head>
    <body>
        <div id="site_container" class="container">

            <header id="header">
                <div id="profile_info">
                    <img src="img/avatar.jpg" id="avatar" alt="avatar" />
                    <p>Welcome <strong>rzepak</strong>. <a href="#">Log out?</a></p>
                    <p>System messages: 3. <a href="#">Read?</a></p>
                    <p class="last_login">Last login: 21:03 12.05.2009</p>
                </div>
                <div id="logo">
                    <h1>
                        <a href="/">AdmintTheme</a>
                    </h1>
                </div>
            </header>

            <div id="content">
                <!-- Echo our content using Twig library -->
                {{ layout().content|raw }}
            </div>

            <footer id="footer" class="clearfix">
                <p class="left">AdminTheme - Ultimate Admin Panel Solution</p>
                <p class="right">© {{ currentDate|date('Y') }} AdminTheme by rzepak</p>
            </footer>
        </div>
    </body>
</html>